PICS :=\
  000_title\
  010_hardware\
  020_device\
  030_device_cfg\
  040_graphene\
  050_bfdata\
  060_devrole\
  070_nmr_progs\

#  070_sweep\
#  090_components\
#  091_dev\

TEXTS := pres

include ../Makefile.inc
