PICS :=\
  000_title\
  010_hardware\
  020_device\
  030_device_cfg\
  040_device_spp\
  050_graphene\
  060_devrole\
  070_sweep\
  080_bfdata\
  090_components\
  091_dev\

TEXTS := pres

include ../Makefile.inc
