PICS := \
  000_title\
  010_he\
  020_he_phase\
  030_sup_he3\
  040_phase1\
  050_phase2\
  052_ph2_modes\
  054_ph2_waves\
  060_ferro\
  070_he3_order\
  080_he3_modes\
  081_he3_modes1\
  090_spinwaves\
  100_leggett_eq\
  110_linear_nmr\
  120_hpd\
  999_black\

TEXTS := pres

include ../Makefile.inc

pics/100_leggett_eq.fig: tex/020_spwaves.tex
pics/090_spinwaves.fig: tex/FSO.tex
pics/090_spinwaves.fig: tex/FM.tex
