PICS := \
  000_title\
  010_he3\
  015_ferro\
  030_modes\
  040_spinwaves\
  050_exp\
  070_suhl\
  071_suhl\
  072_suhl\
  080_vort\
  100_concl

TEXTS := pres

include ../Makefile.inc

pics/100_concl.fig: tex/concl.tex
pics/040_spinwaves.fig: tex/fdip.tex
