PICS := \
  000title 010he3b 020nmr 030pulse\
  040rel 050zrel 060phdep\
  070peaks 071peaks2p 072peaks_temp\
  100concl 105black

TEXTS := pres

include ../Makefile.inc

pics/050zrel.fig:  tex/core_m.tex
pics/050zrel.fig:  tex/core_rel.tex
pics/050zrel.fig:  tex/core_en.tex
pics/060phdep.fig: tex/hdep.tex
pics/060phdep.fig: tex/pdep.tex
pics/070peaks.fig: tex/minigap.tex} \001
pics/100concl.fig: tex/concl.tex
