PICS  = abstr_image\
        000_title\
        010_he3\
        020_spwaves\
        030_HPD\
        040_exp\
        050_exp\
        060_res\
        070_the\
        080_num\
        999_black\

TEXTS = abstract pres

include ../Makefile.inc

pics/020_spwaves.fig: tex/020_spwaves.tex
